"""DocSpec-owned immutable records."""

from docspec.domain.content import (
    AcquisitionDisposition,
    CandidateFile,
    CapturedFile,
    DerivedRecord,
    EvidenceCoordinate,
    EvidenceMapping,
    ProcessorDisposition,
    Representation,
    Segment,
    SourceItem,
    SourceItemState,
)
from docspec.domain.jobs import (
    ChangeKind,
    DocumentEntry,
    DocumentStore,
    FailureClass,
    FailureRecord,
    StoreState,
    StoreVerdict,
)
from docspec.domain.execution import (
    EXECUTE_AND_DELIVER_OPERATION_ID,
    ExecutionHandoff,
    ExecutionLimits,
    ExecutionProfile,
    StoreTask,
    StoreTaskResult,
    StoreTaskStatus,
    iter_store_tasks,
    summarize_store_tasks,
)
from docspec.domain.plans import ProcessingPlan, StagePolicy, WorkLimits
from docspec.domain.maintenance import BlobRetentionSet, ReleaseCompactionReceipt
from docspec.domain.policies import (
    AcceptedFailurePolicy,
    DataUsePolicy,
    ProcessorExecutionScope,
    ProviderEvidence,
    ProviderEvidenceMode,
    ProviderInteractionEvidence,
    RetentionPolicy,
    RetryPolicy,
)
from docspec.domain.processors import (
    ProcessorCacheMode,
    ProcessorCachePolicy,
    ProcessorDescription,
    ProcessorInput,
    ProcessorItemLimits,
    ProcessorPayload,
    ProcessorRequest,
    ProcessorResult,
    ProcessorResourceIdentity,
    ProcessorResourceKind,
    ProcessorSet,
)
from docspec.domain.profiles import ProfileDescription, ProfileGovernance, ProfilePin, ProfileRole, ProfileSet
from docspec.domain.receipts import CatalogCommitReceipt, DeliveryReceipt, RunReceipt
from docspec.domain.release import DocumentRelease
from docspec.domain.references import ArtifactRef, BlobRef, DocumentReleaseRef, LayerRef, SourceCatalogRef, StoreRef
from docspec.domain.scale import ScaleProfile

__all__ = [
    "AcquisitionDisposition",
    "AcceptedFailurePolicy",
    "ArtifactRef",
    "BlobRef",
    "BlobRetentionSet",
    "CandidateFile",
    "CapturedFile",
    "CatalogCommitReceipt",
    "ChangeKind",
    "DeliveryReceipt",
    "DataUsePolicy",
    "DerivedRecord",
    "DocumentEntry",
    "DocumentRelease",
    "DocumentReleaseRef",
    "DocumentStore",
    "EvidenceCoordinate",
    "EvidenceMapping",
    "EXECUTE_AND_DELIVER_OPERATION_ID",
    "ExecutionHandoff",
    "ExecutionLimits",
    "ExecutionProfile",
    "FailureClass",
    "FailureRecord",
    "LayerRef",
    "ProcessingPlan",
    "ProcessorCacheMode",
    "ProcessorCachePolicy",
    "ProcessorDescription",
    "ProcessorDisposition",
    "ProcessorExecutionScope",
    "ProcessorInput",
    "ProcessorItemLimits",
    "ProcessorPayload",
    "ProcessorRequest",
    "ProcessorResult",
    "ProcessorResourceIdentity",
    "ProcessorResourceKind",
    "ProcessorSet",
    "ProfileDescription",
    "ProfileGovernance",
    "ProfilePin",
    "ProfileRole",
    "ProfileSet",
    "ProviderEvidence",
    "ProviderEvidenceMode",
    "ProviderInteractionEvidence",
    "Representation",
    "ReleaseCompactionReceipt",
    "RetentionPolicy",
    "RetryPolicy",
    "RunReceipt",
    "ScaleProfile",
    "Segment",
    "SourceCatalogRef",
    "SourceItem",
    "SourceItemState",
    "StagePolicy",
    "StoreState",
    "StoreTask",
    "StoreTaskResult",
    "StoreTaskStatus",
    "StoreRef",
    "StoreVerdict",
    "WorkLimits",
    "iter_store_tasks",
    "summarize_store_tasks",
]
