"""Deterministic, source-grounded document processing primitives."""

from docspec.processing.artifacts import (
    RepresentationPayload,
    SegmentPayload,
    build_segment,
    verify_representation_evidence,
    verify_segment_evidence,
    verify_segment_representation,
)
from docspec.domain.content import EvidenceMapping
from docspec.processing.extraction import (
    DefaultExtractorRegistry,
    ExtractionReceipt,
    ExtractionResult,
    HtmlExtractor,
    ImageExtractor,
    JsonExtractor,
    LazyPypdfExtractor,
    TextExtractor,
    XmlExtractor,
)
from docspec.processing.processors import (
    ContentStatisticsProcessor,
    ProcessorResult,
)
from docspec.domain.processors import (
    ProcessorCacheMode,
    ProcessorCachePolicy,
    ProcessorDescription,
    ProcessorInput,
    ProcessorItemLimits,
    ProcessorResourceIdentity,
    ProcessorResourceKind,
)
from docspec.processing.bounded_segmentation import (
    BOUNDED_SEGMENTER_ID,
    BOUNDED_TEXT_KINDS,
    EXCLUDED_EMPTY,
    EXCLUDED_NOT_EVIDENCE_ELIGIBLE,
    BoundedSegment,
    BoundedSegmentation,
    BoundedSegmentationError,
    BoundedSegmentationReceipt,
    BoundedSegmenter,
    BoundedSegmentSettings,
    ExcludedRegion,
    SegmentContext,
    SegmentCoverage,
    TokenCounter,
)
from docspec.processing.segmentation import (
    DefaultSegmenterRegistry,
    PageSegmenter,
    ParagraphSegmenter,
    RecordSegmenter,
    SegmentationReceipt,
    WholeImageSegmenter,
)

__all__ = [
    "BOUNDED_SEGMENTER_ID",
    "BOUNDED_TEXT_KINDS",
    "BoundedSegment",
    "BoundedSegmentation",
    "BoundedSegmentationError",
    "BoundedSegmentationReceipt",
    "BoundedSegmenter",
    "BoundedSegmentSettings",
    "build_segment",
    "ContentStatisticsProcessor",
    "DefaultExtractorRegistry",
    "DefaultSegmenterRegistry",
    "EvidenceMapping",
    "EXCLUDED_EMPTY",
    "EXCLUDED_NOT_EVIDENCE_ELIGIBLE",
    "ExcludedRegion",
    "ExtractionReceipt",
    "ExtractionResult",
    "HtmlExtractor",
    "ImageExtractor",
    "JsonExtractor",
    "LazyPypdfExtractor",
    "PageSegmenter",
    "ParagraphSegmenter",
    "ProcessorCacheMode",
    "ProcessorCachePolicy",
    "ProcessorDescription",
    "ProcessorInput",
    "ProcessorItemLimits",
    "ProcessorResourceIdentity",
    "ProcessorResourceKind",
    "ProcessorResult",
    "RecordSegmenter",
    "RepresentationPayload",
    "SegmentationReceipt",
    "SegmentContext",
    "SegmentCoverage",
    "SegmentPayload",
    "TextExtractor",
    "TokenCounter",
    "verify_representation_evidence",
    "verify_segment_evidence",
    "verify_segment_representation",
    "WholeImageSegmenter",
    "XmlExtractor",
]
