"""Compare two synthetic SQLite ledger write paths; neither is a native-binding baseline.

Run: uv run --frozen python docs/history/probes/2026-09-13-sqlite-ledger-binding-probe.py [N ...]

Ledger-shaped rows (result_id, execution_id, definition_id, outcome, fingerprint,
created_at), primary key plus one secondary index, WAL, one transaction per
timing, both durability settings:
  T_sql      pure-SQL insert and commit of N rows generated by a recursive CTE
  T_cte      the CTE's row generation without insert, with EVERY column referenced
             so SQLite cannot skip the formatting; diagnostic only, not an additive
             cost estimate
  T_python   prepared N-row pyarrow table -> bounded tuples -> executemany -> commit
Arrow source preparation and database/schema creation are outside both write
timers, and both write timers include commit. The SQL path generates rows while
the Python path reads a prepared table, so their difference does not isolate
binding overhead or bound a native implementation's benefit. Do not subtract the
diagnostic aggregate -- an earlier subtraction estimate is withdrawn -- or
extrapolate these synthetic rows into a production capacity claim.
"""
import os, sqlite3, sys, tempfile, time
import pyarrow as pa

ROWS = ("SELECT 'r:'||printf('%040x',i) a, 'x:'||printf('%040x',i) b, 'd:'||printf('%040x',i%1000) c, "
        "'ok' d, 'f:'||printf('%040x',i/4) e, i f FROM s")
def cte(n): return f"WITH RECURSIVE s(i) AS (SELECT 0 UNION ALL SELECT i+1 FROM s WHERE i < {n-1})"
tmp_context = tempfile.TemporaryDirectory(prefix="docspec-ledger-probe-")
tmp = tmp_context.name

def fresh(sync):
    con = sqlite3.connect(os.path.join(tmp, f"ledger-{time.time_ns()}.sqlite"))
    con.executescript(f"""PRAGMA journal_mode=WAL; PRAGMA synchronous={sync};
        CREATE TABLE results(result_id TEXT PRIMARY KEY, execution_id TEXT NOT NULL,
            definition_id TEXT NOT NULL, outcome TEXT NOT NULL, fingerprint TEXT NOT NULL,
            created_at INTEGER NOT NULL);
        CREATE INDEX results_fp ON results(fingerprint);""")
    return con

def timed(fn):
    t0 = time.perf_counter(); fn(); return time.perf_counter() - t0

sizes = [int(a) for a in sys.argv[1:]] or [1_000_000, 4_000_000]
if any(n <= 0 for n in sizes):
    raise SystemExit("Row counts must be positive")
print(f"sqlite {sqlite3.sqlite_version}  python {sys.version.split()[0]}  pyarrow {pa.__version__}")
for N in sizes:
    mem = sqlite3.connect(":memory:")
    t_cte = timed(lambda: mem.execute(
        f"{cte(N)} SELECT sum(length(a)+length(b)+length(c)+length(d)+length(e)+f) FROM ({ROWS})").fetchone())
    table = pa.table({"a": [f"r:{i:040x}" for i in range(N)], "b": [f"x:{i:040x}" for i in range(N)],
                      "c": [f"d:{i % 1000:040x}" for i in range(N)], "d": ["ok"] * N,
                      "e": [f"f:{i // 4:040x}" for i in range(N)], "f": list(range(N))})
    mem.close()
    print(f"N={N:,} diagnostic CTE + formatting + aggregate {t_cte:.3f} s; not an insert-cost baseline")
    for sync in ("NORMAL", "FULL"):
        con = fresh(sync)
        def sql_path():
            with con:
                con.execute(f"{cte(N)} INSERT INTO results {ROWS}")
        t_sql = timed(sql_path)
        assert con.execute("SELECT count(*) FROM results").fetchone()[0] == N; con.close()
        con = fresh(sync)
        def python_path():
            with con:
                for batch in table.to_batches(max_chunksize=50_000):
                    con.executemany("INSERT INTO results VALUES (?,?,?,?,?,?)",
                                    zip(*[c.to_pylist() for c in batch.columns]))
        t_py = timed(python_path)
        assert con.execute("SELECT count(*) FROM results").fetchone()[0] == N; con.close()
        print(f"  synchronous={sync:6s} SQL generation + insert + commit {t_sql:.3f} s | "
              f"prepared Arrow + Python binding + insert + commit {t_py:.3f} s")
tmp_context.cleanup()
