"""Does Python row binding matter relative to SQLite's own insert cost for a ledger?

Run: uv run --frozen python docs/history/probes/2026-09-13-sqlite-ledger-binding-probe.py [N ...]

Ledger-shaped rows (result_id, execution_id, definition_id, outcome, fingerprint, created_at),
primary key plus one secondary index, WAL, one transaction per timing, both durability settings:
  T_sql      pure-SQL insert of N rows generated by a recursive CTE (no Python per row)
  T_cte      the CTE's row generation without insert, with EVERY column referenced so SQLite
             cannot skip the formatting; SQLite insert floor = T_sql - T_cte
  T_python   realistic Python path: N-row pyarrow table -> tuples -> executemany
The first version of this probe used a count-only baseline, which let SQLite skip the
formatting and understated the possible native saving by about half. Corrected 2026-09-13.
Results are recorded in docs/history/2026-09-13-core-model-implementation-plan-review.md.
"""
import os, sqlite3, sys, tempfile, time
import pyarrow as pa

ROWS = ("SELECT 'r:'||printf('%040x',i) a, 'x:'||printf('%040x',i) b, 'd:'||printf('%040x',i%1000) c, "
        "'ok' d, 'f:'||printf('%040x',i/4) e, i f FROM s")
def cte(n): return f"WITH RECURSIVE s(i) AS (SELECT 0 UNION ALL SELECT i+1 FROM s WHERE i < {n-1})"
tmp = tempfile.mkdtemp()

def fresh(sync):
    con = sqlite3.connect(os.path.join(tmp, f"ledger-{time.time_ns()}.sqlite"))
    con.executescript(f"""PRAGMA journal_mode=WAL; PRAGMA synchronous={sync};
        CREATE TABLE results(result_id TEXT PRIMARY KEY, execution_id TEXT NOT NULL,
            definition_id TEXT NOT NULL, outcome TEXT NOT NULL, fingerprint TEXT NOT NULL,
            created_at INTEGER NOT NULL);
        CREATE INDEX results_fp ON results(fingerprint);""")
    return con

def timed(fn):
    t0 = time.perf_counter(); fn(); return time.perf_counter() - t0

sizes = [int(a) for a in sys.argv[1:]] or [1_000_000, 4_000_000]
print(f"sqlite {sqlite3.sqlite_version}  python {sys.version.split()[0]}  pyarrow {pa.__version__}")
for N in sizes:
    mem = sqlite3.connect(":memory:")
    t_cte = timed(lambda: mem.execute(
        f"{cte(N)} SELECT sum(length(a)+length(b)+length(c)+length(d)+length(e)+f) FROM ({ROWS})").fetchone())
    table = pa.table({"a": [f"r:{i:040x}" for i in range(N)], "b": [f"x:{i:040x}" for i in range(N)],
                      "c": [f"d:{i % 1000:040x}" for i in range(N)], "d": ["ok"] * N,
                      "e": [f"f:{i // 4:040x}" for i in range(N)], "f": list(range(N))})
    print(f"N={N:,}  baseline (CTE + formatting, all columns forced) {t_cte:.2f} s")
    for sync in ("NORMAL", "FULL"):
        con = fresh(sync)
        t_sql = timed(lambda: con.execute(f"{cte(N)} INSERT INTO results {ROWS}")); con.commit()
        assert con.execute("SELECT count(*) FROM results").fetchone()[0] == N; con.close()
        con = fresh(sync)
        def python_path():
            with con:
                for batch in table.to_batches(max_chunksize=50_000):
                    con.executemany("INSERT INTO results VALUES (?,?,?,?,?,?)",
                                    zip(*[c.to_pylist() for c in batch.columns]))
        t_py = timed(python_path)
        assert con.execute("SELECT count(*) FROM results").fetchone()[0] == N; con.close()
        floor = t_sql - t_cte
        print(f"  synchronous={sync:6s} floor {floor:5.2f} s ({N/floor:>9,.0f} rows/s) | "
              f"python path {t_py:5.2f} s ({N/t_py:>9,.0f} rows/s) | "
              f"largest possible native saving {t_py-floor:4.2f} s = {100*(t_py-floor)/t_py:.0f}%")
